apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  env: demo
  type: frontend
spec:
 containers:
 - name: ngingx-container
   image: nginx
   ports:
   - containerPort: 80 
 nodeName: cka-cluster3-worker